env:
  browser: false
  es6: true
  node: true
parserOptions:
  sourceType: module
  ecmaVersion: 2022
settings:
  import/resolver:
    babel-module:
plugins:
  - prettier
  - import
  - module-resolver
extends:
  - "eslint:recommended"
  - "prettier"
  - "plugin:import/recommended"
rules:
  "prettier/prettier": error