env:
  browser: true
  es6: true
  jest: true
extends:
  - airbnb
  - airbnb/hooks
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:prettier/recommended'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - prettier
  - unused-imports
ignorePatterns:
  - node_modules
rules:
  no-unused-vars:
    - off # Handled by unused-imports
  unused-imports/no-unused-imports:
    - error
  unused-imports/no-unused-vars:
    - warn
    - vars: all
      varsIgnorePattern: '^_'
      args: after-used
      argsIgnorePattern: '^_'
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
  react/jsx-filename-extension:
    - off
    - extensions:
        - '.js'
        - '.jsx'
  jsx-a11y/anchor-is-valid:
    - error
    - components:
        - 'a'
  react/jsx-props-no-spreading:
    - off
  prettier/prettier:
    - error
  no-empty:
    - error
    - allowEmptyCatch: true
  no-var:
    - error
  no-alert:
    - error
  no-console:
    - error
  no-shadow-restricted-names:
    - error
  no-restricted-exports:
    - off
  no-restricted-syntax:
    - error
  array-bracket-spacing:
    - error
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  camelcase:
    - warn
  comma-spacing:
    - error
  key-spacing:
    - error
  no-lonely-if:
    - error
  no-multiple-empty-lines:
    - error
  no-spaced-func:
    - error
  no-trailing-spaces:
    - error
  object-curly-spacing:
    - error
    - always
  one-var:
    - error
    - never
  semi:
    - error
    - always
  keyword-spacing:
    - error
  space-before-blocks:
    - error
  space-in-parens:
    - error
    - never
  space-infix-ops:
    - error
  space-unary-ops:
    - error
  spaced-comment:
    - error
    - always
  no-underscore-dangle:
    - off
